name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Ensure firebase.json exists
        run: |
          if [ ! -f firebase.json ]; then
            echo '{
              "hosting": {
                "public": "public",
                "ignore": [
                  "firebase.json",
                  "**/.*",
                  "**/node_modules/**"
                ],
                "rewrites": [
                  {
                    "source": "**",
                    "destination": "/index.html"
                  }
                ]
              }
            }' > firebase.json
          fi

      - name: Create package.json if it doesn't exist
        run: |
          if [ ! -f package.json ]; then
            echo '{
              "name": "madj101",
              "version": "1.0.0",
              "description": "Mobile App Development for Juniors",
              "main": "index.js",
              "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1",
                "build": "webpack --config webpack.config.js"
              },
              "author": "Raydo Matthee",
              "license": "ISC",
              "dependencies": {
                "webpack": "^5.0.0",
                "webpack-cli": "^4.0.0"
              }
            }' > package.json
          fi

      - name: Create webpack.config.js if it doesn't exist
        run: |
          if [ ! -f webpack.config.js ]; then
            echo 'const path = require("path");

          module.exports = {
          entry: "./web-portal/js/scripts.js",
          output: {
          filename: "bundle.js",
          path: path.resolve(__dirname, "web-portal/js")
          },
          mode: "production"
          };' > webpack.config.js
          fi
          
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
