name: Setup Environment

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create directories
        run: |
          mkdir -p course-materials/lectures
          mkdir -p course-materials/exercises
          mkdir -p course-materials/resources
          mkdir -p practical-lab-work
          mkdir -p web-portal
          mkdir -p web-portal/css
          mkdir -p web-portal/js
          mkdir -p web-portal/assets

      - name: Verify directory structure
        run: |
          ls -la course-materials
          ls -la practical-lab-work
          ls -la web-portal

      - name: Create initial course files
        run: |
          echo "# Lectures" > course-materials/lectures/README.md
          echo "# Exercises" > course-materials/exercises/README.md
          echo "# Resources" > course-materials/resources/README.md
          echo "# Practical Lab Work" > practical-lab-work/README.md
          cat <<EOF > web-portal/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Mobile App Development for Juniors</title>
              <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;700&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="css/styles.css">
              <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js"></script>
              <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js"></script>
              <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-firestore.js"></script>
          </head>
          <body>
              <header>
                  <h1>Mobile App Development for Juniors</h1>
                  <h2>Course Code: MADJ101</h2>
                  <h3>Building Foundational Skills for Future App Developers</h3>
              </header>
              <nav>
                  <ul>
                      <li><a href="lectures.html">Lectures</a></li>
                      <li><a href="exercises.html">Exercises</a></li>
                      <li><a href="resources.html">Resources</a></libulletin>
                      <li><a href="practical-lab.html">Practical Lab Work</a></li>
                  </ul>
              </nav>
              <main>
                  <section id="content">
                      <h2>Welcome to the Course Portal</h2>
                      <p>Navigate through the sections to access course materials and lab exercises.</p>
                  </section>
              </main>
              <footer>
                  <p>&copy; 2024 Skunkworks (Pty) Ltd. All rights reserved.</p>
              </footer>
              <script src="js/scripts.js"></script>
          </body>
          </html>
          EOF

      - name: Create package.json if it doesn't exist
        run: |
          if [ ! -f package.json ]; then
            cat <<EOF > package.json
            {
              "name": "madj101",
              "version": "1.0.0",
              "description": "Mobile App Development for Juniors",
              "main": "index.js",
              "scripts": {
                "test": "echo 'Error: no test specified' && exit 1",
                "build": "webpack --config webpack.config.js"
              },
              "author": "Raydo Matthee",
              "license": "ISC",
              "dependencies": {
                "webpack": "^5.0.0",
                "webpack-cli": "^4.0.0"
              },
              "devDependencies": {
                "@babel/core": "^7.0.0",
                "@babel/preset-env": "^7.0.0",
                "babel-loader": "^8.0.0"
              }
            }
            EOF
          fi

      - name: Create webpack.config.js if it doesn't exist
        run: |
          if [ ! -f webpack.config.js ]; then
            cat <<EOF > webpack.config.js
            const path = require("path");

            module.exports = {
              entry: "./web-portal/js/scripts.js",
              output: {
                filename: "bundle.js",
                path: path.resolve(__dirname, "web-portal/js")
              },
              mode: "production",
              module: {
                rules: [
                  {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                      loader: "babel-loader",
                      options: {
                        presets: ["@babel/preset-env"]
                      }
                    }
                  }
                ]
              }
            };
            EOF
          fi

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COURSE_MADJ101 }}
          channelId: live
          projectId: course-madj101
